### ISSUE TITLE
`TypeLoadException` when creating the `AspNetCoreKernel`

### ISSUE THREAD

**Issue by NameOfTheDragon** [lord-executor/Ninject.Web.AspNetCore#14]
I'm trying to get this going, and I've followed your instructions (I think) pretty carefully. But I get this TypeLoadException:

> System.TypeLoadException
  HResult=0x80131522
  Message=Method 'Resolve' in type 'Ninject.Web.AspNetCore.Components.ConstrainedGenericBindingResolver' from assembly 'Ninject.Web.AspNetCore, Version=8.0.1.0, Culture=neutral, PublicKeyToken=cc1f638e4e277871' does not have an implementation.
  Source=Ninject.Web.AspNetCore
  StackTrace:
   at Ninject.Web.AspNetCore.AspNetCoreKernel.AddComponents()
   at Ninject.KernelBase..ctor(IComponentContainer components, INinjectSettings settings, INinjectModule[] modules)
   at Ninject.KernelBase..ctor(INinjectSettings settings, INinjectModule[] modules)
   at Ninject.StandardKernel..ctor(INinjectSettings settings, INinjectModule[] modules)
   at Ninject.Web.AspNetCore.AspNetCoreKernel..ctor(INinjectSettings settings, INinjectModule[] modules)
   at TA.Starquest.Web.Program.CreateNinjectKernel() in Z:\repos\Tigra-Astronomy\TA.Starquest\TA.Starquest.Web\Program.cs:line 41
   at Ninject.Web.Common.SelfHost.NinjectSelfHostBootstrapper.<>c__DisplayClass1_0.<.ctor>b__0()
   at Ninject.Web.Common.Bootstrapper.Initialize(Func`1 createKernelCallback)
   at Ninject.Web.Common.SelfHost.NinjectSelfHostBootstrapper..ctor(Func`1 createKernelCallback, Object[] selfHostConfigurations)
   at TA.Starquest.Web.Program.Main(String[] args) in Z:\repos\Tigra-Astronomy\TA.Starquest\TA.Starquest.Web\Program.cs:line 29

The exception happens on this line:
```csharp
        var kernel = new AspNetCoreKernel(settings);
```
in this method:

```csharp
    private static IKernel CreateNinjectKernel()
    {
        var settings = new NinjectSettings();
        // Unfortunately, in .NET Core projects, referenced NuGet assemblies are not copied to the output directory
        // in a normal build which means that the automatic extension loading does not work _reliably_ and it is
        // much more reasonable to not rely on that and load everything explicitly.
        settings.LoadExtensions = false;

        var kernel = new AspNetCoreKernel(settings);

        kernel.Load(typeof(AspNetCoreHostConfiguration).Assembly);
        kernel.Load(new StarquestModule());

        return kernel;
    }
```
This is confusing, because I can see in the source code that method does have an implementation, so I'm not really sure what this even means. Any ideas?

**Comment by NameOfTheDragon** [comment]
Um, I think I figured it out. Looks like I somehow got a beta release of Ninject 4.0 installed, which of course breaks everything.

On that basis, I'm closing the issue.

P.S.. I would have used a discussion for this if they were enabled...... :)
